### ISSUE TITLE
Need example to setup it together with ccache

### ISSUE THREAD

**Issue by o01eg** [airvzxf/cache-anything-new-action#1]
I found this action when searched to cache installed packages but also I need to cache ccache files. I didn't find a way to have two caches. Could it possible to setup up this action to cache installed packages before build and ccache files after build?

**Comment by airvzxf** [comment]
Are you looking for something like this? [Speeding up C++ GitHub Actions using ccache](https://cristianadam.eu/20200113/speeding-up-c-plus-plus-github-actions-using-ccache/)

**Comment by o01eg** [comment]
I found it but I don't understand how to use it together.

**Comment by airvzxf** [comment]
Could you send me the link of  your GitHub repository? And actions that you want to perform? Is it private or public?

**Comment by o01eg** [comment]
https://github.com/freeorion/freeorion/pull/3263/files

**Comment by airvzxf** [comment]
I'm working in your challenge, which use my cache action for build this awesome game.

I forked the Free Orion repository and implement your changes, I'm doing some testings: [build-github-actions-airvzxf](https://github.com/airvzxf/freeorion/tree/build-github-actions-airvzxf). My pull request for testing is the [#3270](https://github.com/freeorion/freeorion/pull/3270)

First, the way that you are implementing my action allows to cache the apt update and the installation from scratch the first time, the second time it won't install anything only copy all the generated files. Basically, the same as the installation. It saves around 5 minutes.

Second, when I finish testing the installation, I'll try to implement the ccache to your build, after this you can implement my example branch into your PR.

Final note:
I didn't play FreeOrion and I noticed that it is the free version of [Master of Orion](https://en.wikipedia.org/wiki/Master_of_Orion) which was released in 1993, but I started to play on 2005 the MS-DOS game [Ascendancy](https://en.wikipedia.org/wiki/Ascendancy_(video_game) which was release on 1995. It was my favorite game. Both looks similar using the 4x. However, thanks for choose my action.

**Comment by airvzxf** [comment]
Some results.

Talking about the first point in the last comment, you are saving around 10~12 minutes avoiding the installation using my action. I added the results below. Next step is check how to use `ccache` with my action.

From your PR's 8 days ago:
```text
# First time

Build FreeOrion on Ubuntu 18.04 (Bionic)
https://github.com/freeorion/freeorion/runs/1620578728
APT Installation: 10m 12s
Cmake: 27m 44s

Build headless FreeOrion on Ubuntu 18.04 (Bionic)
https://github.com/freeorion/freeorion/runs/1620578661
APT Installation: 12m 5s
Cmake: 18m 15s

# -----------------------------------------------------

# Second time

Build FreeOrion on Ubuntu 18.04 (Bionic)
https://github.com/freeorion/freeorion/runs/1620748519
APT Installation: 8s
Cmake: 28m 13s

Build headless FreeOrion on Ubuntu 18.04 (Bionic)
https://github.com/freeorion/freeorion/runs/1620578661
APT Installation: 9s
Cmake: 15m 25s

# -----------------------------------------------------

Saved time in the APT Installation around of 10-12 minutes
```

From my PR's tests:
```text
# First time

Build FreeOrion on Ubuntu 18.04 (Bionic)
succeeded in 44m 49s
APT Installation: 9m 24s
Cmake: 33m 38s

Build headless FreeOrion on Ubuntu 18.04 (Bionic)
succeeded in 30m 43s
APT Installation: 10m 25s
Cmake: 18m 58s

# -----------------------------------------------------

# Second time

Build FreeOrion on Ubuntu 18.04 (Bionic)
succeeded in 31m 41s
APT Installation: 9m 24s
Cmake: 33m 38s

Build headless FreeOrion on Ubuntu 18.04 (Bionic)
succeeded in 21m 41s 
APT Installation: 8s
Cmake: 31m 18s

# -----------------------------------------------------

Saved time in the APT Installation around of 9-10 minutes
```

**Comment by airvzxf** [comment]
Finally, I understand why it's hard to implement in the GitHub actions but not impossible.

This is the logic about the cache:

1. Create or apply the cache from the directory `~/.ccache` with `actions/cache`.
2. Build the game with `make`.
3. The new cache was generated in `~/.ccache`.
4. The new cache is not stored because it was created or applied before the `make` process.

The solution proposed in the article “[Speeding up C++ GitHub Actions using ccache](https://cristianadam.eu/20200113/speeding-up-c-plus-plus-github-actions-using-ccache/)” is about to create a new cache key every time and take the last one, but I don't understand yet how to it solves the step #4. 

I'm still doing more tests and hopefully, I'll get a final version for this challenge.

**Comment by o01eg** [comment]
Thanks for efforts.

**Comment by airvzxf** [comment]
You're welcome, as a community and Open-Source philosophy we are stronger than the private companies.

BTW, It's working. I am doing the final details, but the article was correct. It creates the GitHub cache with the key name using the timestamp at the end every time that all the steps are finished, it automatically checks the differences generated by the 'ccache' and create a new GitHub cache.

**Comment by airvzxf** [comment]
Succeeded!

The code changes are in [build.yml](https://github.com/airvzxf/freeorion/blob/build-github-actions-airvzxf/.github/workflows/build.yml) which is the only file that I modified. Basically, I added two steps in every Linux job: `Prepare ccache timestamp` and the `ccache files`. However, I'll add in this comment the final code.

The result of the executed actions are in [this link](https://github.com/freeorion/freeorion/actions).

Let me know when you apply your changes to cancel the [PR for test](https://github.com/freeorion/freeorion/pull/3270).

[Test #33](https://github.com/freeorion/freeorion/actions/runs/466724940)
```text
Build FreeOrion on Ubuntu 18.04 (Bionic)
Succeeded in 1m 2s

Build headless FreeOrion on Ubuntu 18.04 (Bionic)
Succeeded in 38s
```

`.github/workflows/build.yml`
```yml
name: Build FreeOrion and run unit tests
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  push:
    branches:
      - master
jobs:
  build-linux:
    name: Build FreeOrion on Ubuntu 18.04 (Bionic)
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: build-linux-install-cache-id
        with:
          path: ${{ runner.temp }}/cache-build-linux-install
          key: build-linux-install-cache-key-v1.0
      - uses: airvzxf/cache-anything-new-action@v1.0
        with:
          script: 'install-build.sh'
          is_cached: ${{ steps.build-linux-install-cache-id.outputs.cache-hit }}
          cache: ${{ runner.temp }}/cache-build-linux-install
          snapshot: '/'
          exclude: '/boot /data /dev /mnt /proc /run /sys'
      - name: Prepare ccache timestamp
        id: build-linux-ccache-timestamp
        shell: cmake -P {0}
        run: |
          string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
          message("::set-output name=timestamp::${current_date}")
      - name: ccache files
        uses: actions/cache@v1.1.0
        with:
          path: ${{ runner.temp }}/ccache
          key: build-linux-ccache-${{ steps.build-linux-ccache-timestamp.outputs.timestamp }}
          restore-keys: |
            build-linux-ccache-
      - name: Build
        env:
          CACHE_NAME: linux
          CCACHE_DIR: ${{ runner.temp }}/ccache
          CMAKE_BUILD_PARALLEL_LEVEL: 2
        run: |
          echo "----------------------------------------"
          ccache -s || true
          echo "----------------------------------------"
          mkdir build
          cd build
          cmake -DBUILD_TESTING=ON ..
          cmake --build .
          echo "----------------------------------------"
          ccache -s || true
          echo "----------------------------------------"
      - name: Test
        run: |
          cd build
          cmake --build . --config Release --target unittest || echo Failure
  build-linux-headless:
    name: Build headless FreeOrion on Ubuntu 18.04 (Bionic)
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: build-linux-headless-install-cache-id
        with:
          path: ${{ runner.temp }}/cache-build-linux-headless-install
          key: build-linux-headless-install-cache-key-v1.0
      - uses: airvzxf/cache-anything-new-action@v1.0
        with:
          script: 'install-build.sh'
          is_cached: ${{ steps.build-linux-headless-install-cache-id.outputs.cache-hit }}
          cache: ${{ runner.temp }}/cache-build-linux-headless-install
          snapshot: '/'
          exclude: '/boot /data /dev /mnt /proc /run /sys'
      - name: Prepare ccache timestamp
        id: build-linux-headless-ccache-timestamp
        shell: cmake -P {0}
        run: |
          string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
          message("::set-output name=timestamp::${current_date}")
      - name: ccache files
        uses: actions/cache@v1.1.0
        with:
          path: ${{ runner.temp }}/ccache
          key: build-linux-headless-ccache-${{ steps.build-linux-headless-ccache-timestamp.outputs.timestamp }}
          restore-keys: |
            build-linux-headless-ccache-
      - name: Build
        env:
          CACHE_NAME: linux-headless
          CCACHE_DIR: ${{ runner.temp }}/ccache
          CMAKE_BUILD_PARALLEL_LEVEL: 2
        run: |
          echo "----------------------------------------"
          ccache -s || true
          echo "----------------------------------------"
          mkdir build
          cd build
          cmake -DBUILD_CLIENT_GG=OFF -DBUILD_TESTING=ON ..
          cmake --build .
          echo "----------------------------------------"
          ccache -s || true
          echo "----------------------------------------"
      - name: Test
        run: |
          cd build
          cmake --build . --config Release --target unittest || echo Failure
```
